### ISSUE TITLE
GPU is on but my intel graphic card is used

### ISSUE THREAD

**Issue by DraGiuS** [xdever/linux_gpu_switch#1]
When i set gpu in "on" mode, in lspci it appear to be in use, but when i start glxinfo it show me that mesa is used.

**Comment by RobertCsordas** [comment]
Because glxinfo shows which card is used to accelerate your graphics. The whole point of this script is to turn on the card without any graphics subsystem started, just purely for compute. For example for training neural networks, physics simulations, etc. Run nvidia-smi, and you should see the card available there.
